openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/hireds:
    x-router-controller: hiredsController
    get:
      description: Returns all hireds
      operationId: getHireds
      responses:
        200:
          description: Hired list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/hired'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
   
                  
  /api/v1/hireds/{year}:
    x-router-controller: hiredsController
    get:
      description: Returns a single hired by its id
      operationId: findByyear
      parameters:
        - required: true
          name: id
          description: id of the hired to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Hired found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hired'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    hired:
        type: object
        required:
          - year
        properties:
          year:
            type: number
          name:
            type: string
          code:
            type: string
          country:
            type: string
          founded:
            type: number
          national:
            type: boolean
          logo:
            type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true